### ISSUE TITLE
It is not possible to run the code

### ISSUE THREAD

**Issue by iblancasa** [SoyGema/Tensorflow_CodeLab_Wide-Deep_learning#3]
I have been trying to run the codelab and I was not able to do it. The code has some errors. I tried to fix all of them on this branch: https://github.com/iblancasa/Tensorflow_CodeLab_Wide-Deep_learning/tree/fix-run

I am using Python 2 and the requirements.txt from https://github.com/codelab-tf-got/codelab-tf-got.github.io

Also, if I run the Python script from https://github.com/codelab-tf-got/codelab-tf-got.github.io and all seems to run OK. Also the file ``Wide+deep.py`` is too similar to ``net_mk1.py``.

I found the following error and I don't know how to fix it:
```python
python Wide+deep.py --training_mode learn_runner --model_dir model --model_type 'wide_n_deep' --steps 200
/home/israel/projects/Tensorflow_CodeLab_Wide-Deep_learning/asd/local/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
2017-08-24 01:07:56,446 - net_mk1 - DEBUG - Number of columns after removing nulls: 1946 (before: 1946)
model directory = model
2017-08-24 01:07:56,450 - net_mk1 - INFO - Learning rates (wide, deep) = [0.001, 0.003]
2017-08-24 01:07:56,450 - net_mk1 - INFO - Got wide columns [_RealValuedColumn(column_name='age', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='popularity', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='numDeadRelations', dimension=1, default_value=None, dtype=tf.float32, normalizer=None)]
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
WARNING:tensorflow:From Wide+deep.py:161: calling __init__ (from tensorflow.contrib.learn.python.learn.estimators.dnn_linear_combined) with fix_global_step_increment_bug=False is deprecated and will be removed after 2017-04-15.
Instructions for updating:
Please set fix_global_step_increment_bug=True and update training steps in your pipeline. See pydoc for details.
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': None, '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f91c5566710>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': ''}
Traceback (most recent call last):
  File "Wide+deep.py", line 313, in <module>
    tf.app.run()
  File "/home/israel/projects/Tensorflow_CodeLab_Wide-Deep_learning/asd/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "Wide+deep.py", line 309, in main
    train_and_eval()
  File "Wide+deep.py", line 301, in train_and_eval
    steps=FLAGS.train_steps
  File "/home/israel/projects/Tensorflow_CodeLab_Wide-Deep_learning/asd/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "/home/israel/projects/Tensorflow_CodeLab_Wide-Deep_learning/asd/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 430, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/israel/projects/Tensorflow_CodeLab_Wide-Deep_learning/asd/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 925, in _train_model
    features, labels = input_fn()
TypeError: 'NoneType' object is not iterable
```

Please, could you help me?

Thanks :+1:

**Comment by SoyGema** [comment]
can you try with net_mk1.py?

**Comment by iblancasa** [comment]
Ok, it is working now.

Thanks! @SoyGema , you rock!
